- src/client/js/client.js
- src/client/js/components/PaymentForm/AddFunds/LoginButton.js
- src/client/js/components/PaymentForm/AddFunds/index.js
- src/client/js/components/PaymentForm/Amount.js
- src/client/js/components/PaymentForm/index.js
- src/server/stripe.js
https://github.com/webRunes/webGold-WRIO-App/issues/41
> Add funds: remove harcoded values

- config.json.default
https://github.com/webRunes/WRIO-InternetOS/issues/224
> Added config.json.default template

- Dockerfile
Avoided to use symlinks, all node_modules installed to srv
> Dockerfile optimization

- src/client/js/client.js
- src/client/js/components/PaymentForm/Amount.js
- src/server/ethereum-route.js
> Fixed client issues

- src/client/js/admin.js
- src/client/views/admin.html
- src/index.js
- src/server/ethereum-route.js
Coinadmin improvements
Ether feeds list improved
> Fixed auth to coinadmin page

- src/client/js/admin.js
- src/client/js/components/PaymentForm/Amount.js
- src/client/js/components/PaymentForm/BitcoinForm.js
- src/client/js/components/PaymentForm/index.js
- src/client/views/admin.html
- src/server/blockchain.info.js
- src/server/dbmodels/etherfeed.js
- src/server/dbmodels/invoice.js
- src/server/ethereum-route.js
- src/server/ethereum.js
https://github.com/webRunes/webGold-WRIO-App/issues/56
> Added missing files, admin extending, stablility improvements

- docker-compose.yml
- package.json
- server-test.js
- server.js
- src/index.js
- src/server/blockchain.info.js
- src/server/db.js
- src/server/dbmodels/invoice.js
- src/server/dbmodels/wriouser.js
- src/server/ethereum.js
- test/apitest.js
- test/blockchain.js
Blockhain request fixes.
webGold tests now using local db instead of production one, before each test db fixtures created.
> Blockchain unit tests improved

- src/server/blockchain.info.js
- src/server/ethereum-route.js
- src/server/ethereum.js
Every transaction now is checked on local node, without mining. If succeeds, transaction is mined.
> Ethereum transaction pre-flight checking added

- Dockerfile
- index.htm
- src/server/ethereum-route.js
> Fee reporing added in donate API call

- src/server/ethereum-route.js
> Prevent donate to same user

- src/index.js
- src/server/ethereum-route.js
- wrio_app.js
To allow check balance from another WRIO apps
> Access control changed

- package.json
- src/client/js/admin.js
- src/server/blockchain.info.js
- src/server/dbmodels/donations.js
- src/server/dbmodels/emissions.js
- src/server/dbmodels/etherfeed.js
- src/server/dbmodels/invoice.js
- src/server/ethereum-route.js
- src/server/ethereum.js
Added blockchain notification logging to the db,
> Added timestamp sorting and formatting, blockchain notification logging to the db

- Dockerfile
- package.json
Install ethereum to docker image
> Fix npm problems

- server.js
Reverts webRunes/webGold-WRIO-App#112
> Revert "To restart Travis"

- ethereum/deploy.js
- package.json
- src/server/ethereum-node/index.js
- src/server/ethereum-route.js
- src/server/ethereum.js
https://github.com/webRunes/webGold-WRIO-App/issues/120
> Ethereum integration: Ethereum web3 library upgrade, prepayment lock bug fixed

- src/server/ethereum-route.js
- src/server/ethereum.js
https://github.com/webRunes/webGold-WRIO-App/issues/68
> Promised payment: Prepayments fixed, expiry added

- gulpfile.js
- src/server/ethereum-route.js
- test/apitest.js
Nodemon multiple restart fixed during development process
https://github.com/webRunes/webGold-WRIO-App/issues/120
> Ethereum integration #120: Detailed error returned during donate

- src/server/ethereum-route.js
- src/server/wriologin.js
https://github.com/webRunes/webGold-WRIO-App/issues/137
>  No funds #137: Added detailed info about user balance: amount in blockhain, and amount promised displayed

- src/client/js/stores/TransactionStore.js
- src/client/js/transactions.js
- src/server/user-stats.js
Fix text, add no records, added progress gif
https://github.com/webRunes/webGold-WRIO-App/issues/150
> Transactions #150 Added prepayments to the transactions view, misc fixes

- package.json
- src/client/js/stores/TransactionStore.js
- src/client/js/transactions.js
Add transactions error handling
> Fix webgold build error

- src/client/js/transactions.js
https://github.com/webRunes/webGold-WRIO-App/issues/156
> Transactions UI #156

- src/client/js/transactions.js
> Breadcrumb hotfix

- Dockerfile
- src/client/views/webgold-transactions.htm
- test/blockchain.js
Fix tests 
https://github.com/webRunes/WRIO-InternetOS/issues/17
> ADD SSL #14 Fix transaction page http links

- .travis.yml
- package.json
- src/client/views/admin.htm
- src/client/views/index.htm
https://github.com/webRunes/WRIO-InternetOS/issues/17
> ADD SSL #17 Fix https urls

- src/index.js
- src/server/admin/route.js
- src/server/blockchain.info.js
- src/server/ethereum-route.js
- src/server/user-stats.js
- src/server/wriologin.js
- test/apitest.js
Refactoring, code more clean to read.
Introduce wrapper for exception handling, each route doesn't need to handle its exceptions, expeptions caught globally.
> Introduce middleware-based authentification, using service-to-service auth for /donate

- package.json
- src/index.js
- src/server/DonateProcessor.js
- src/server/PendingPaymentProcessor.js
- src/server/blockchain.info.js
- src/server/dbmodels/wriouser.js
- src/server/ethereum-route.js
- src/server/ethereum.js
- src/server/payments/RateGetter.js
- src/server/wriologin.js
- test/apitest.js
Request of rates to blockchain.info are cached now
Auth fixes
Bugfixes
/free_wrg now available only for local development
> Refactoring of Pending Payments and Donate code

- gulpfile.js
- server.js
- src/server/DonateProcessor.js
Add transpile step for optimization
> Fix semicolon

- package.json
- src/client/js/components/BalanceLine.js
- src/client/js/components/PaymentForm/PaymentData.js
- src/client/js/transactions.js
Fix amount display
Fix no items display
> Fix amount display

- src/client/js/client.js
- src/client/js/components/PaymentForm/index.js
> Add autoheight sending

- src/client/js/components/PaymentForm/Amount.js
https://github.com/webRunes/webGold-WRIO-App/issues/156
> Fix default exchange rate problem #156

- src/client/js/transactions.js
https://github.com/webRunes/webGold-WRIO-App/issues/150
> Add initiated message #150

- hub/index.html
https://github.com/webRunes/WRIO-InternetOS/issues/647
> htm -> html #647

- src/server/controllers/ethereum.js
- src/server/ethereum/ethereum.js
- src/server/models/emissions.js
- src/server/routes/ethereum-route.js
Add time left for WRG emission
> Add tx status monitoring

- src/server/controllers/ethereum.js
- src/server/routes/admin.js
https://github.com/webRunes/webGold-WRIO-App/issues/396#issuecomment-295436170
> Fix RTX units display

- contract/src/WRG.sol
- src/client/js/components/PresaleForm/Amount.js
- src/client/js/components/PresaleForm/PaymentData.js
- src/client/js/components/PresaleForm/index.js
- src/client/js/presale.js
- src/constant.js
Fix url cancel button
Fix price constant
> Fix currency converter form operation algorithm
